.TH "src Directory Reference" 3 "Sun Jun 19 2022" "Version 0.0.2" "1-wire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1wire\&.cpp\fP"
.br
.RI "works with 1-wire chip IO with the chips stored in eeprom and the state in ram\&. "
.ti -1c
.RI "file \fB1wire\&.h\fP"
.br
.in -1c
