.TH "chip1wire_T" 3 "Sun Jun 19 2022" "Version 0.0.2" "1-wire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chip1wire_T
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <1wire\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBaddr\fP [8]"
.br
.ti -1c
.RI "byte \fBowIndex\fP"
.br
.ti -1c
.RI "byte \fBstate\fP"
.br
.ti -1c
.RI "byte \fBioBitmsk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB63\fP of file \fB1wire\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "byte chip1wire_T::addr[8]"

.PP
Definition at line \fB65\fP of file \fB1wire\&.h\fP\&.
.SS "byte chip1wire_T::ioBitmsk"

.PP
Definition at line \fB69\fP of file \fB1wire\&.h\fP\&.
.SS "byte chip1wire_T::owIndex"

.PP
Definition at line \fB67\fP of file \fB1wire\&.h\fP\&.
.SS "byte chip1wire_T::state"

.PP
Definition at line \fB68\fP of file \fB1wire\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 1-wire from the source code\&.
