.TH "test/main.cpp" 3 "Sun Jun 19 2022" "Version 0.0.2" "1-wire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <ui_io\&.h>\fP
.br
\fC#include <defs\&.h>\fP
.br
\fC#include '1wire\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtermIO\fP"
.br
.ti -1c
.RI "#define \fBtestEqu\fP(T,  R,  V)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_get1wireIDsIndex\fP ()"
.br
.ti -1c
.RI "void \fBtest_get1wireIOno\fP ()"
.br
.ti -1c
.RI "void \fBtest_get1wireChipTypeIOPins\fP ()"
.br
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBOneWire_mem\fP \fBv1wire\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define termIO"

.PP
Definition at line \fB12\fP of file \fBmain\&.cpp\fP\&.
.SS "#define testEqu(T, R, V)"
\fBValue:\fP
.PP
.nf
   Serial\&.print( F(" Test " # T "( " # V " ) Expect: " #R)  );   x = T(V);\
   if(R==x){ Serial\&.println(F("\t\t\e[32m Pas\e[38;5;10msed \e[37m ") ); }else{ Serial\&.print(F("\t\t\e[91m Failed\e[93m , returned: ") );  Serial\&.println(x);}
.fi
.PP
Definition at line \fB14\fP of file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void loop ()"

.PP
Definition at line \fB79\fP of file \fBmain\&.cpp\fP\&.
.SS "void setup ()"

.PP
Definition at line \fB52\fP of file \fBmain\&.cpp\fP\&.
.SS "void test_get1wireChipTypeIOPins ()"

.PP
Definition at line \fB41\fP of file \fBmain\&.cpp\fP\&.
.SS "void test_get1wireIDsIndex ()"

.PP
Definition at line \fB17\fP of file \fBmain\&.cpp\fP\&.
.SS "void test_get1wireIOno ()"

.PP
Definition at line \fB31\fP of file \fBmain\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBOneWire_mem\fP v1wire"

.PP
Definition at line \fB51\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 1-wire from the source code\&.
