.TH "md_changelog" 3 "Mon Nov 21 2022" "Version 0.0.1" "1-wire_io" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_changelog \- changelog 
.PP
v0\&.0\&.2 renamed int8_t OneWire_mem::get1wireFromEepromIndex( byte index ) to int8_t OneWire_mem::loadFromStorage(byte index) some type fixes moved some globals to class variables\&. 
