.TH "switch1wire_TX" 3 "Sun Jun 19 2022" "Version 0.0.2" "1-wire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
switch1wire_TX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <1wire\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBchipType\fP"
.br
.ti -1c
.RI "byte \fBaddr\fP [6]"
.br
.ti -1c
.RI "byte \fBcrc\fP"
.br
.ti -1c
.RI "byte \fBroomNum\fP"
.br
.ti -1c
.RI "byte \fBpinChan\fP"
.br
.ti -1c
.RI "byte \fBslotI\fP = 19"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB86\fP of file \fB1wire\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "byte switch1wire_TX::addr[6]"

.PP
Definition at line \fB88\fP of file \fB1wire\&.h\fP\&.
.SS "byte switch1wire_TX::chipType"

.PP
Definition at line \fB87\fP of file \fB1wire\&.h\fP\&.
.SS "byte switch1wire_TX::crc"

.PP
Definition at line \fB90\fP of file \fB1wire\&.h\fP\&.
.SS "byte switch1wire_TX::pinChan"

.PP
Definition at line \fB94\fP of file \fB1wire\&.h\fP\&.
.SS "byte switch1wire_TX::roomNum"

.PP
Definition at line \fB91\fP of file \fB1wire\&.h\fP\&.
.SS "byte switch1wire_TX::slotI = 19"

.PP
Definition at line \fB97\fP of file \fB1wire\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 1-wire from the source code\&.
