.TH "switch1wire_TE" 3 "Sun Jun 19 2022" "Version 0.0.2" "1-wire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
switch1wire_TE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <1wire\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBswitch1wire_T\fP \fBe\fP"
.br
.ti -1c
.RI "byte \fBwa1wirePos\fP = 19"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB102\fP of file \fB1wire\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBswitch1wire_T\fP switch1wire_TE::e"

.PP
Definition at line \fB103\fP of file \fB1wire\&.h\fP\&.
.SS "byte switch1wire_TE::wa1wirePos = 19"

.PP
Definition at line \fB104\fP of file \fB1wire\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 1-wire from the source code\&.
